// <auto-generated/>
using Microsoft.Kiota.Abstractions;
using Ready4Tech.Kiota.Client.V1.Api.Geolocation.Item;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace Ready4Tech.Kiota.Client.V1.Api.Geolocation {
    /// <summary>
    /// Builds and executes requests for operations under \v1\api\geolocation
    /// </summary>
    public class GeolocationRequestBuilder : BaseRequestBuilder {
        /// <summary>Gets an item from the Ready4Tech.Kiota.Client.v1.api.geolocation.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        public WithCityItemRequestBuilder this[string position] { get {
            var urlTplParams = new Dictionary<string, object>(PathParameters);
            urlTplParams.Add("city", position);
            return new WithCityItemRequestBuilder(urlTplParams, RequestAdapter);
        } }
        /// <summary>
        /// Instantiates a new GeolocationRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GeolocationRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/api/geolocation", pathParameters) {
        }
        /// <summary>
        /// Instantiates a new GeolocationRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GeolocationRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/api/geolocation", rawUrl) {
        }
    }
}
