/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
import { DawnduskRequestBuilder } from './dawndusk/';
import { GeolocationRequestBuilder } from './geolocation/';
import { BaseRequestBuilder, type RequestAdapter } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/api
 */
export class ApiRequestBuilder extends BaseRequestBuilder<ApiRequestBuilder> {
    /**
     * The dawndusk property
     */
    public get dawndusk(): DawnduskRequestBuilder {
        return new DawnduskRequestBuilder(this.pathParameters, this.requestAdapter);
    }
    /**
     * The geolocation property
     */
    public get geolocation(): GeolocationRequestBuilder {
        return new GeolocationRequestBuilder(this.pathParameters, this.requestAdapter);
    }
    /**
     * Instantiates a new ApiRequestBuilder and sets the default values.
     * @param pathParameters The raw url or the Url template parameters for the request.
     * @param requestAdapter The request adapter to use to execute the requests.
     */
    public constructor(pathParameters: Record<string, unknown> | string | undefined, requestAdapter: RequestAdapter) {
        super(pathParameters, requestAdapter, "{+baseurl}/v1/api", (x, y) => new ApiRequestBuilder(x, y));
    }
}
/* tslint:enable */
/* eslint-enable */
