/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
import { createCoordinateFromDiscriminatorValue, createErrorPayloadFromDiscriminatorValue, deserializeIntoErrorPayload, serializeErrorPayload, type Coordinate, type ErrorPayload } from '../../../../models/';
import { BaseRequestBuilder, HttpMethod, RequestInformation, type Parsable, type ParsableFactory, type RequestAdapter, type RequestConfiguration, type RequestOption } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /v1/api/geolocation/{city}
 */
export class WithCityItemRequestBuilder extends BaseRequestBuilder<WithCityItemRequestBuilder> {
    /**
     * Instantiates a new WithCityItemRequestBuilder and sets the default values.
     * @param pathParameters The raw url or the Url template parameters for the request.
     * @param requestAdapter The request adapter to use to execute the requests.
     */
    public constructor(pathParameters: Record<string, unknown> | string | undefined, requestAdapter: RequestAdapter) {
        super(pathParameters, requestAdapter, "{+baseurl}/v1/api/geolocation/{city}", (x, y) => new WithCityItemRequestBuilder(x, y));
    }
    /**
     * Get geolocation from a city name
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a Promise of Coordinate
     */
    public get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<Coordinate | undefined> {
        const requestInfo = this.toGetRequestInformation(
            requestConfiguration
        );
        const errorMapping = {
            "400": createErrorPayloadFromDiscriminatorValue,
            "401": createErrorPayloadFromDiscriminatorValue,
            "404": createErrorPayloadFromDiscriminatorValue,
            "500": createErrorPayloadFromDiscriminatorValue,
        } as Record<string, ParsableFactory<Parsable>>;
        return this.requestAdapter.sendAsync<Coordinate>(requestInfo, createCoordinateFromDiscriminatorValue, errorMapping);
    }
    /**
     * Get geolocation from a city name
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns a RequestInformation
     */
    public toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation {
        const requestInfo = new RequestInformation(HttpMethod.GET, this.urlTemplate, this.pathParameters);
        requestInfo.configure(requestConfiguration);
        requestInfo.headers.tryAdd("Accept", "application/json");
        return requestInfo;
    }
}
/* tslint:enable */
/* eslint-enable */
