// <auto-generated/>
using Microsoft.Kiota.Abstractions;
using Ready4Tech.Kiota.Client.V1.Api.Dawnduskcalculation.Item;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace Ready4Tech.Kiota.Client.V1.Api.Dawnduskcalculation {
    /// <summary>
    /// Builds and executes requests for operations under \v1\api\dawnduskcalculation
    /// </summary>
    public class DawnduskcalculationRequestBuilder : BaseRequestBuilder {
        /// <summary>Gets an item from the Ready4Tech.Kiota.Client.v1.api.dawnduskcalculation.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        public WithCalculationTypeItemRequestBuilder this[string position] { get {
            var urlTplParams = new Dictionary<string, object>(PathParameters);
            urlTplParams.Add("calculationType", position);
            return new WithCalculationTypeItemRequestBuilder(urlTplParams, RequestAdapter);
        } }
        /// <summary>
        /// Instantiates a new DawnduskcalculationRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DawnduskcalculationRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/api/dawnduskcalculation", pathParameters) {
        }
        /// <summary>
        /// Instantiates a new DawnduskcalculationRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DawnduskcalculationRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/api/dawnduskcalculation", rawUrl) {
        }
    }
}
