// <auto-generated/>
using Microsoft.Kiota.Abstractions;
using Ready4Tech.Kiota.Client.V1.Api.Dawndusk.Item;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System;
namespace Ready4Tech.Kiota.Client.V1.Api.Dawndusk {
    /// <summary>
    /// Builds and executes requests for operations under \v1\api\dawndusk
    /// </summary>
    public class DawnduskRequestBuilder : BaseRequestBuilder {
        /// <summary>Gets an item from the Ready4Tech.Kiota.Client.v1.api.dawndusk.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        public WithCalculationTypeItemRequestBuilder this[string position] { get {
            var urlTplParams = new Dictionary<string, object>(PathParameters);
            urlTplParams.Add("calculationType", position);
            return new WithCalculationTypeItemRequestBuilder(urlTplParams, RequestAdapter);
        } }
        /// <summary>
        /// Instantiates a new DawnduskRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DawnduskRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/api/dawndusk", pathParameters) {
        }
        /// <summary>
        /// Instantiates a new DawnduskRequestBuilder and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DawnduskRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/api/dawndusk", rawUrl) {
        }
    }
}
