// <auto-generated/>
using Microsoft.Kiota.Abstractions.Serialization;
using Ready4Tech.Kiota.Client.Models;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System;
namespace Ready4Tech.Kiota.Client.V1.Api.Dawndusk {
    public class DawnduskPostRequestBody : IAdditionalDataHolder, IParsable {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The coordinate property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public Ready4Tech.Kiota.Client.Models.Coordinate? Coordinate { get; set; }
#nullable restore
#else
        public Ready4Tech.Kiota.Client.Models.Coordinate Coordinate { get; set; }
#endif
        /// <summary>The date property</summary>
        public DateTimeOffset? Date { get; set; }
        /// <summary>
        /// Instantiates a new dawnduskPostRequestBody and sets the default values.
        /// </summary>
        public DawnduskPostRequestBody() {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static DawnduskPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode) {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new DawnduskPostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers() {
            return new Dictionary<string, Action<IParseNode>> {
                {"coordinate", n => { Coordinate = n.GetObjectValue<Ready4Tech.Kiota.Client.Models.Coordinate>(Ready4Tech.Kiota.Client.Models.Coordinate.CreateFromDiscriminatorValue); } },
                {"date", n => { Date = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer) {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<Ready4Tech.Kiota.Client.Models.Coordinate>("coordinate", Coordinate);
            writer.WriteDateTimeOffsetValue("date", Date);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
